  CREATE OR REPLACE PROCEDURE cdx_cims.add_departments(department_uuid uuid,
                                                     dep_id_pers uuid,
                                                     dep_id_struct varchar(255),
                                                     dep_name varchar(255),
                                                     organization_uuid uuid,
                                                     org_name varchar(255),
                                                     parent_department_uuid uuid,
                                                     parent_department_name varchar(255),
                                                     chief_person_uuid uuid,
                                                     chief_person_name varchar(255),
                                                     is_work_center integer,
                                                     is_work_center_str text,
                                                     quality_check integer,
                                                     quality_check_str text,
                                                     whse_check integer,
                                                     whse_check_str text,
                                                     deleted integer,
                                                     deleted_str text,
                                                     creation_date timestamp with time zone,
                                                     user_created varchar(64),
                                                     external_id varchar(256),
                                                     dep_guid_pers uuid,
                                                     dep_guid_struct uuid,
                                                     dep_type_id integer,
                                                     dep_type_name varchar(512))

    language plpgsql
as
$$

BEGIN

    if organization_uuid is NULL then
        INSERT INTO departments_user_v ("dep_id_pers",
                                        "dep_id_struct",
                                        "dep_name",
                                        "organization_uuid",
                                        "org_name",
                                        "parent_department_uuid",
                                        "parent_department_name",
                                        "chief_person_uuid",
                                        "chief_person_name",
                                        "is_work_center",
                                        "is_work_center_str",
                                        "quality_check",
                                        "quality_check_str",
                                        "whse_check",
                                        "whse_check_str",
                                        "deleted",
                                        "deleted_str",
                                        "creation_date",
                                        "user_created",
                                        "external_id",
                                        "dep_guid_pers",
                                        "dep_guid_struct",
                                        "dep_type_id",
                                        "dep_type_name")
        VALUES (dep_id_pers,
                dep_id_struct,
                dep_name,
                organization_uuid,
                org_name,
                parent_department_uuid,
                parent_department_name,
                chief_person_uuid,
                chief_person_name,
                is_work_center,
                is_work_center_str,
                quality_check,
                quality_check_str,
                whse_check,
                whse_check_str,
                deleted,
                deleted_str,
                creation_date,
                user_created,
                external_id,
                dep_guid_pers,
                dep_guid_struct,
                dep_type_id,
                dep_type_name);
    else
        update departments_user_v
        set dep_id_pers= '@dep_id_pers',
            dep_id_struct= '@dep_id_struct',
            dep_name= '@dep_name',
            organization_uuid= '@organization_uuid',
            org_name= '@org_name',
            parent_department_uuid= '@parent_department_uuid',
            parent_department_name= '@parent_department_name',
            chief_person_uuid= '@chief_person_uuid',
            chief_person_name= '@chief_person_name',
            is_work_center= '@is_work_center',
            is_work_center_str= '@is_work_center_str',
            quality_check= '@quality_check',
            quality_check_str= '@quality_check_str',
            whse_check= '@whse_check',
            whse_check_str= '@whse_check_str',
            deleted= '@deleted',
            deleted_str= '@deleted_str',
            creation_date= '@creation_date',
            user_created= '@user_created',
            external_id= '@external_id',
            dep_guid_pers= '@dep_guid_pers',
            dep_guid_struct= '@dep_guid_struct',
            dep_type_id= '@dep_type_id',
            dep_type_name= '@dep_type_name'
        WHERE department_uuid = '@department_uuid';
    END if;
    COMMIT;

END
$$;


SELECT department_uuid,
       dep_id_pers,
       dep_id_struct,
       dep_name,
       organization_uuid,
       org_name,
       parent_department_uuid,
       parent_department_name,
       chief_person_uuid,
       chief_person_name,
       is_work_center,
       is_work_center_str,
       quality_check,
       quality_check_str,
       whse_check,
       whse_check_str,
       deleted,
       deleted_str,
       creation_date,
       user_created,
       external_id,
       dep_guid_pers,
       dep_guid_struct,
       dep_type_id,
       dep_type_name
FROM cdx_cims.departments_user_v;
